const organizationState = {
    newYork: "New York",
    alabama: "Alabama",
    alaska: "Alaska",
    arizona: "Arizona",
    arkansas: "Arkansas",
    california: "California",
    colorado: "Colorado",
    connecticut: "Connecticut",
    delaware: "Delaware",
    districtOfColumbia: "District Of Columbia",
    florida: "Florida",
    georgia: "Georgia",
    hawaii: "Hawaii",
    idaho: "Idaho",
    illinois: "Illinois",
    indiana: "Indiana",
    iowa: "Iowa",
    kentucky: "Kentucky",
    louisiana: "Louisiana",
    maine: "Maine",
    maryland: "Maryland",
    massachusetts: "Massachusetts",
    michigan: "Michigan",
    minnesota: "Minnesota",
    mississippi: "Mississippi",
    missouri: "Missouri",
    montana: "Montana",
    nebraska: "Nebraska",
    nevada: "Nevada",
    newHampshire: "New Hampshire",
    newJersey: "New Jersey",
    newMexico: "New Mexico",
    northCarolina: "North Carolina",
    northDakota: "North Dakota",
    ohio: "Ohio",
    oklahoma: "Oklahoma",
    oregon: "Oregon",
    pennsylvania: "Pennsylvania",
    puertoRico: "Puerto Rico",
    rhodeIsland: "Rhode Island",
    southCarolina: "South Carolina",
    southDakota: "South Dakota",
    tennessee: "Tennessee",
    texas: "Texas",
    utah: "Utah",
    vermont: "Vermont",
    virginia: "Virginia",
    washington: "Washington",
    wisconsin: "Wisconsin",
    westVirginia: "West Virginia",
    wyoming: "Wyoming",
} as const;

export default Object.freeze(organizationState);