const exportTitles = {
    assessedValueAndRealEstateTaxes: "Assessed Value & Real Estate Taxes",
    certification: "Certification",
    commercialExpenseReimbursement: "Commercial Expense Reimbursement",
    commercialSpace: "Commercial Space",
    commercialStabilizedRentRoll: "Commercial Stabilized Rent Roll",
    commercialVacancyAndCollectionLoss: "Commercial Vacancy & Collection Loss",
    comparableSalesAdjustmentGrid: "Comparable Sales Adjustment Grid",
    comparableSalesOutline: "Comparable Sales Outline",
    concludedValuePerUnit: "Concluded Value Per Unit",
    currentCommercialRentRoll: "Current Commercial Rent Roll",
    cumulativePricePerUnit: "Cumulative Price Per Unit",
    currentResidentialRentRoll: "Current Residential Rent Roll",
    definitionOfMarketValue: "Definition of Market Value",
    estimatedOperatingExpenses: "Estimated Operating Expenses",
    exposureTime: "Exposure Time",
    highestAndBestUse: "Highest & Best Use",
    identificationOfTheClient: "Identification of the Client",
    incomeCapitalizationApproach: "Income Capitalization Approach",
    intendedUseAndUser: "Intended Use & User",
    leaseStructure: "Lease Structure",
    letterOfEngagement: "Letter of Engagement",
    marketingTime: "Marketing Time",
    mortgageComponent: "Mortgage Component",
    potentialGrossCommercialRent: "Potential Gross Commercial Rent",
    potentialGrossResidentialIncome: "Potential Gross Residential Income",
    propertyRightsAppraised: "Property Rights Appraised",
    qualifications: "Qualifications",
    rentControlledIncreases: "Rent Controlled Increases",
    siteDescription: "Site Description",
    stabilizedIncomeAndExpenses: "Stabilized Income & Expenses ",
    submarketAnalyses: "Submarket Analyses",
    summaryOfSalientFactsAndConclusions: "Summary of Salient Facts & Conclusions",
    taxableAssessedValue: "Taxable Assessed Value",
    threats: "Threats",
    valueOpinionViaTheSalesComparisonApproach: "Value Opinion via the Sales Comparison Approach"
} as const;

export default Object.freeze(exportTitles);