const proFormaType = {
    potentialResIncome: "Potential Residential Income",
    potentialUndeterminedCommercialIncome: "Potential Undetermined Commercial Income",
    potentialCommercialIncome: "Potential Commercial Income",
    parkingIncome: "Parking Income",
    laundryIncome: "Laundry Income",
    storageIncome: "Storage Income",
    potentialRealEstateTaxesReimbursement: "Potential Real Estate Taxes Reimbursement",
    otherIncome: "Other Income",
    potentialGrossIncome: "Potential Gross Income",
    residentialVCLoss: "Less Residential V/C Loss",
    effectiveGrossIncome: "Effective Gross Income",
    operatingExpenses: "Operating Expenses",
    realEstateTaxes: "Real Estate Taxes",
    insurance: "Insurance",
    electricity: "Electricity",
    fuel: "Fuel",
    waterAndSewer: "Water & Sewer",
    utilities: "Utilities",
    repairAndMaintenance: "Repairs & Maintenance",
    payrollBenefits: "Payroll & Benefits",
    generalAndAdministrative: "General & Administrative",
    legalAndProfessional: "Legal & Professional Fees",
    miscellaneous: "Miscellaneous",
    managementFees: "Management Fees",
    replacementsAndReserves: "Replacement Reserves",
    totalOperatingExpenses: "Total Operating Expenses",
    totalOperatingExpensesExTaxes: "Total Operating Expenses (Excl. RE Taxes)",
    netOperatingIncome: "Net Operating Income",
    operatingExpenseRatio: "Operating Expense Ratio"
} as const;

export default Object.freeze(proFormaType);