export enum Tag {
    property = "@property",
    income = "@income",
    commercial = "@commercial",
    stabilized_rent_roll = "@stabilized_rent_roll",
    in_place_rent_roll = "@in_place_rent_roll",
    comp_plex = "@comp_plex",
    snapshot_tests = "@snapshot_tests",
    expense_forecast = "@expense_forecast",
    fix = "@fix",
    find_comps = "@find_comps",
    adjust_comps = "@adjust_comps",
    rent_comps = "@rent_comps",
    residential = "@residential",
    commercial_units = "@commercial_units",
    sales = "@sales",
    value_conclusion = "@value_conclusion",
    check_export = "@check_export",
    tax_info = "@tax_info",
    report = "@report",
    client ="@client"
}