export default {
    capRateRoundingFactor: 'capRateRoundingFactor',
    asStabilizedAmount: 'asStabilizedAmount',
    asCompleteAmount: 'asCompleteAmount',
    asStabilizedResRentLossItem: 'asStabilizedRentLossItem',
    asStabilizedCommercialRentLossItem: 'asStabilizedCommercialRentLossItem',
    asStabilizedCommercialUndeterminedRentLossItem: 'asStabilizedCommercialUndeterminedRentLossItem',
    commissionFee: 'commissionFee',
    entrepreneurialStabilizedProfit: 'entrepreneurialProfit',
    asCompleteResRentLossItem: 'asCompleteResRentLossItem',
    asCompleteCommercialRentLossItem: 'asCompleteCommercialRentLossItem',
    asCompleteCommercialUndeterminedRentLossItem: 'asCompleteCommercialUndeterminedRentLossItem',
    buyoutCost: 'buyoutCost',
    entrepreneurialCompleteProfit: 'entrepreneurialProfit',
    asIsMarketAmount: 'asIsMarketAmount',
    asIsMarketFinalAmount: 'asIsMarketFinalAmount',
    renovationBudget: 'renovationBudget',
    asCompleteFinalAmount: 'asCompleteFinalAmount',
    asStabilizedFinalAmount: 'asStabilizedFinalAmount',
    allAsStabilizedLossesAliases: 'allAsStabilizedLossesAliases',
    allAsCompleteLossesAliases: 'allAsCompleteLossesAliases',
    valueConclusionLossesAsStabilizedFileName: 'valueConclusionLossesAsStabilizedFileName',
    valueConclusionLossesACompleteFileName: 'valueConclusionLossesACompleteFileName'
};